version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "${HTTP_FORWARD_PORT:-8080}:${HTTP_PORT:-8080}"
    volumes:
      - .:/app
      - /app/tmp
      - ./pgdata:/var/lib/postgresql/data:ro
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD:-postgres}@postgres:5432/${DATABASE_DATABASE:-postgres}?sslmode=disable
    depends_on:
      - postgres
    env_file: .env
    restart: always

  postgres:
    image: postgres:15-alpine
    ports:
      - ${DATABASE_PORT:-5555}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres1}
      - POSTGRES_DB=${DATABASE_DATABASE:-postgres}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
